unit udmInfoCartao;

interface

uses
  SysUtils, Classes, DBXpress, DB, SqlExpr, FMTBcd, DBClient, Provider,
  Forms, Windows;

type
  TdmInfoCartao = class(TDataModule)
    SQLConnection1: TSQLConnection;
    dstClientes: TSQLDataSet;
    dspClientes: TDataSetProvider;
    cdsClientes: TClientDataSet;
    cdsClientesCLI_CDCLIE: TStringField;
    cdsClientesCLI_NMCLIE: TStringField;
    cdsClientesCLI_NMCART: TStringField;
    cdsClientesCLI_TPPESS: TStringField;
    cdsClientesCLI_DTNASC: TDateField;
    cdsClientesCLI_DTNAS1: TStringField;
    cdsClientesCLI_SXCLIE: TStringField;
    cdsClientesCLI_ESTCIV: TStringField;
    cdsClientesCLI_NRIDEN: TStringField;
    cdsClientesCLI_ORGEMI: TStringField;
    cdsClientesCLI_UFEMIS: TStringField;
    cdsClientesCLI_CPFCGC: TStringField;
    cdsClientesCLI_EMAIL: TStringField;
    cdsClientesCLI_NOMPAI: TStringField;
    cdsClientesCLI_NOMMAE: TStringField;
    cdsClientesCLI_CDBANC: TStringField;
    cdsClientesCLI_FLESPE: TStringField;
    cdsClientesCLI_ENCLIE: TStringField;
    cdsClientesCLI_CEPCLI: TStringField;
    cdsClientesCLI_COMCLI: TStringField;
    cdsClientesCLI_BAICLI: TStringField;
    cdsClientesCLI_CIDCLI: TStringField;
    cdsClientesCLI_UFCLIE: TStringField;
    cdsClientesCLI_FONCLI: TStringField;
    cdsClientesCLI_TIPFON: TStringField;
    cdsClientesCLI_CELCLI: TStringField;
    cdsClientesCLI_TPRESI: TStringField;
    cdsClientesCLI_TMRESI: TStringField;
    cdsClientesCLI_NMEMPR: TStringField;
    cdsClientesCLI_ENEMPR: TStringField;
    cdsClientesCLI_CEPEMP: TStringField;
    cdsClientesCLI_BAEMPR: TStringField;
    cdsClientesCLI_CIEMPR: TStringField;
    cdsClientesCLI_VINEMP: TStringField;
    cdsClientesCLI_TIPEMP: TStringField;
    cdsClientesCLI_TMSERV: TStringField;
    cdsClientesCLI_FONEMP: TStringField;
    cdsClientesCLI_RAMEMP: TStringField;
    cdsClientesCLI_FLPROP: TStringField;
    cdsClientesCLI_NMCARG: TStringField;
    cdsClientesCLI_CGCEMP: TStringField;
    cdsClientesCLI_NOMCJG: TStringField;
    cdsClientesCLI_EMPCJG: TStringField;
    cdsClientesCLI_FONCJG: TStringField;
    cdsClientesCLI_CELCJG: TStringField;
    cdsClientesCLI_CPFCJG: TStringField;
    cdsClientesCLI_ENCORR: TStringField;
    cdsClientesCLI_NMBENS: TStringField;
    cdsClientesCLI_OUTCAR: TStringField;
    cdsClientesCLI_NMREF1: TStringField;
    cdsClientesCLI_FOREF1: TStringField;
    cdsClientesCLI_NMREF2: TStringField;
    cdsClientesCLI_FOREF2: TStringField;
    cdsClientesCLI_DTCADA: TDateField;
    cdsClientesCLI_DTCAD1: TStringField;
    cdsClientesCLI_HOCADA: TStringField;
    cdsClientesCLI_FLSITU: TStringField;
    cdsClientesCLI_CDREPR: TStringField;
    cdsClientesCLI_DATANA: TDateField;
    cdsClientesCLI_DATAN1: TStringField;
    cdsClientesCLI_HORANA: TStringField;
    cdsClientesCLI_USUANA: TStringField;
    cdsClientesCLI_SPCANA: TStringField;
    cdsClientesCLI_LOCANA: TStringField;
    cdsClientesCLI_OBSANA: TBlobField;
    cdsClientesCLI_FLCONV: TStringField;
    cdsClientesCLI_NRCART: TStringField;
    cdsClientesCLI_PEDESC: TFMTBCDField;
    dstParametros: TSQLDataSet;
    dspParametros: TDataSetProvider;
    cdsParametros: TClientDataSet;
    cdsParametrosPAR_NMEMPR: TStringField;
    cdsParametrosPAR_ENEMPR: TStringField;
    cdsParametrosPAR_BAIRRO: TStringField;
    cdsParametrosPAR_CIDADE: TStringField;
    cdsParametrosPAR_CEPEMP: TStringField;
    cdsParametrosPAR_UFEMPR: TStringField;
    cdsParametrosPAR_CGCEMP: TStringField;
    cdsParametrosPAR_INSEST: TStringField;
    cdsParametrosPAR_NRFONE: TStringField;
    cdsParametrosPAR_NUMFAX: TStringField;
    cdsParametrosPAR_DTATUA: TDateField;
    cdsParametrosPAR_LTTEMP: TStringField;
    cdsParametrosPAR_NRTEMP: TFMTBCDField;
    cdsParametrosPAR_GRUSUA: TFMTBCDField;
    cdsParametrosPAR_CDUSUA: TFMTBCDField;
    cdsParametrosPAR_CDCLIE: TFMTBCDField;
    cdsParametrosPAR_CDCRED: TFMTBCDField;
    cdsParametrosPAR_VALCAR: TFMTBCDField;
    cdsParametrosPAR_NRCART: TFMTBCDField;
    cdsParametrosPAR_NRVEND: TFMTBCDField;
    cdsParametrosPAR_LIPARC: TFMTBCDField;
    cdsParametrosPAR_NRSEQU: TFMTBCDField;
    cdsParametrosPAR_FLCAIX: TStringField;
    cdsParametrosPAR_RGINIC: TStringField;
    cdsParametrosPAR_CDNATU: TFMTBCDField;
    cdsParametrosPAR_NRFATU: TFMTBCDField;
    cdsParametrosPAR_NMCEDE: TStringField;
    cdsParametrosPAR_LOCPAGA: TStringField;
    cdsParametrosPAR_NRBOLE: TFMTBCDField;
    cdsParametrosPAR_PEJURO: TFMTBCDField;
    cdsParametrosPAR_NATVEN: TStringField;
    cdsParametrosPAR_DTFATU: TDateField;
    cdsParametrosPAR_QTATRA: TFMTBCDField;
    cdsParametrosPAR_NMPAST: TStringField;
    cdsParametrosPAR_CDCEDE: TStringField;
    cdsParametrosPAR_DIGCED: TStringField;
    cdsParametrosPAR_CDBANC: TStringField;
    cdsParametrosPAR_CDAGEN: TStringField;
    cdsParametrosPAR_DIGAGE: TStringField;
    cdsParametrosPAR_NRCONT: TStringField;
    cdsParametrosPAR_INSTR1: TMemoField;
    cdsParametrosPAR_INSTR2: TMemoField;
    cdsParametrosPAR_IMLOGO: TBlobField;
    dstTipoFone: TSQLDataSet;
    dspTipoFone: TDataSetProvider;
    cdsTipoFone: TClientDataSet;
    cdsClientesCLI_TPFONE: TStringField;
    dstTipoResiden: TSQLDataSet;
    dspTipoResiden: TDataSetProvider;
    cdsTipoResidencia: TClientDataSet;
    cdsClientesCLI_TPRES2: TStringField;
    dstVinculo: TSQLDataSet;
    dspVinculo: TDataSetProvider;
    cdsVinculo: TClientDataSet;
    cdsClientesCLI_VIEMPR: TStringField;
    dstCorrespon: TSQLDataSet;
    dspCorresp: TDataSetProvider;
    cdsCorresp: TClientDataSet;
    cdsClientesCLI_ENCOR2: TStringField;
    dstBancos: TSQLDataSet;
    dspBancos: TDataSetProvider;
    cdsBancos: TClientDataSet;
    cdsClientesCLI_NMBANC: TStringField;
    dstSituacao: TSQLDataSet;
    dspSituacao: TDataSetProvider;
    cdsSituacao: TClientDataSet;
    cdsClientesCLI_NMSITU: TStringField;
    cdsClientesCLI_VLSALA: TFloatField;
    dstPessoa: TSQLDataSet;
    dspPessoa: TDataSetProvider;
    cdsTPPessoa: TClientDataSet;
    cdsTPPessoaPES_TPPESS: TStringField;
    cdsTPPessoaPES_NMDESC: TStringField;
    cdsClientesCLI_TPDESC: TStringField;
    dstSexo: TSQLDataSet;
    dspSexo: TDataSetProvider;
    cdsSexo: TClientDataSet;
    cdsClientesCLI_SXDESC: TStringField;
    dstEstCivil: TSQLDataSet;
    dspEstCivil: TDataSetProvider;
    cdsEstCivil: TClientDataSet;
    cdsClientesCLI_ECDESC: TStringField;
    cdsClientesCLI_VLRESI: TFloatField;
    cdsClientesCLI_VLOUTR: TFloatField;
    cdsClientesCLI_VLBENS: TFloatField;
    cdsClientesCLI_LIMANA: TFloatField;
    dstCredenciados: TSQLDataSet;
    dspCredeciados: TDataSetProvider;
    cdsCredenciados: TClientDataSet;
    cdsCredenciadosCRE_CDCRED: TStringField;
    cdsCredenciadosCRE_NMCRED: TStringField;
    cdsCredenciadosCRE_NMEXTR: TStringField;
    cdsCredenciadosCRE_ENDCRE: TStringField;
    cdsCredenciadosCRE_BACRED: TStringField;
    cdsCredenciadosCRE_CICRED: TStringField;
    cdsCredenciadosCRE_UFCRED: TStringField;
    cdsCredenciadosCRE_CEPCRE: TStringField;
    cdsCredenciadosCRE_NRFONE: TStringField;
    cdsCredenciadosCRE_CDUSUA: TStringField;
    dstBuscaCliente: TSQLDataSet;
    dspBuscaCliente: TDataSetProvider;
    cdsBuscaCliente: TClientDataSet;
    cdsBuscaClienteCLI_CDCLIE: TStringField;
    cdsBuscaClienteCLI_NMCLIE: TStringField;
    cdsBuscaClienteCLI_NMCART: TStringField;
    cdsBuscaClienteCLI_NRIDEN: TStringField;
    cdsBuscaClienteCLI_CPFCGC: TStringField;
    dstBuscaCred: TSQLDataSet;
    dspBuscaCred: TDataSetProvider;
    cdsBuscaCred: TClientDataSet;
    StringField1: TStringField;
    StringField2: TStringField;
    StringField3: TStringField;
    StringField4: TStringField;
    StringField5: TStringField;
    StringField6: TStringField;
    StringField7: TStringField;
    StringField8: TStringField;
    StringField9: TStringField;
    StringField10: TStringField;
    dstCartoes: TSQLDataSet;
    cdsCartoes: TClientDataSet;
    dspCartoes: TDataSetProvider;
    cdsCartoesCAR_NRCART: TStringField;
    cdsCartoesCAR_CDCLIE: TStringField;
    cdsCartoesCAR_DTEMIS: TDateField;
    cdsCartoesCAR_DTEMI1: TStringField;
    cdsCartoesCAR_VLLIMI: TFMTBCDField;
    cdsCartoesCAR_DIAFAT: TIntegerField;
    cdsCartoesCAR_FLDEPE: TStringField;
    cdsCartoesCAR_FLSITU: TStringField;
    cdsCartoesCAR_DTUTIL: TDateField;
    cdsCartoesCAR_DTUTI1: TStringField;
    cdsCartoesCAR_HOUTIL: TStringField;
    cdsCartoesCAR_VLANTE: TFMTBCDField;
    cdsCartoesCAR_VLCRED: TFMTBCDField;
    cdsCartoesCAR_DTPAGA: TDateField;
    cdsCartoesCAR_DTPAG1: TStringField;
    cdsCartoesCAR_CDUSUA: TStringField;
    cdsCartoesCAR_NMTITU: TStringField;
    cdsCartoesCAR_DTVALI: TStringField;
    dstSitCartao: TSQLDataSet;
    dspSitCartao: TDataSetProvider;
    cdsSitCartao: TClientDataSet;
    cdsCartoesCAR_NMSITU: TStringField;
    dstDiaFatura: TSQLDataSet;
    dspDiaFatura: TDataSetProvider;
    cdsDiaFatura: TClientDataSet;
    cdsCartoesCAR_FATDIA: TStringField;
    cdsClientesCLI_CDUSUA: TStringField;
    dstMovimento: TSQLDataSet;
    dspMovimento: TDataSetProvider;
    cdsMovimento: TClientDataSet;
    cdsSitCartaoSIT_SIGSIT: TStringField;
    cdsSitCartaoSIT_NMSITU: TStringField;
    dstDebito: TSQLDataSet;
    dspDebito: TDataSetProvider;
    cdsDebito: TClientDataSet;
    cdsDebitoDEB_NRVEND: TStringField;
    cdsDebitoDEB_NRCART: TStringField;
    cdsDebitoDEB_CDCLIE: TStringField;
    cdsDebitoDEB_CDCRED: TStringField;
    cdsDebitoDEB_DTREFE: TStringField;
    cdsDebitoDEB_QTPARC: TIntegerField;
    cdsDebitoDEB_NRPARC: TIntegerField;
    cdsDebitoDEB_VLPARC: TFloatField;
    cdsDebitoDEB_DTVENC: TDateField;
    cdsDebitoDEB_DTVEN1: TStringField;
    cdsDebitoDEB_DTFATU: TDateField;
    cdsDebitoDEB_DTFAT1: TStringField;
    cdsDebitoDEB_TPMOVI: TStringField;
    cdsDebitoDEB_FLSITU: TStringField;
    cdsDebitoDEB_NRFATU: TStringField;
    cdsDebitoDEB_VLDESC: TFloatField;
    cdsCartoesCAR_VLUTIL: TFloatField;
    dstParametrosPAR_NMEMPR: TStringField;
    dstParametrosPAR_ENEMPR: TStringField;
    dstParametrosPAR_BAIRRO: TStringField;
    dstParametrosPAR_CIDADE: TStringField;
    dstParametrosPAR_CEPEMP: TStringField;
    dstParametrosPAR_UFEMPR: TStringField;
    dstParametrosPAR_CGCEMP: TStringField;
    dstParametrosPAR_INSEST: TStringField;
    dstParametrosPAR_NRFONE: TStringField;
    dstParametrosPAR_NUMFAX: TStringField;
    dstParametrosPAR_DTATUA: TDateField;
    dstParametrosPAR_LTTEMP: TStringField;
    dstParametrosPAR_NRTEMP: TFMTBCDField;
    dstParametrosPAR_GRUSUA: TFMTBCDField;
    dstParametrosPAR_CDUSUA: TFMTBCDField;
    dstParametrosPAR_CDCLIE: TFMTBCDField;
    dstParametrosPAR_CDCRED: TFMTBCDField;
    dstParametrosPAR_VALCAR: TFMTBCDField;
    dstParametrosPAR_NRCART: TFMTBCDField;
    dstParametrosPAR_NRVEND: TFMTBCDField;
    dstParametrosPAR_LIPARC: TFMTBCDField;
    dstParametrosPAR_NRSEQU: TFMTBCDField;
    dstParametrosPAR_FLCAIX: TStringField;
    dstParametrosPAR_RGINIC: TStringField;
    dstParametrosPAR_CDNATU: TFMTBCDField;
    dstParametrosPAR_NRFATU: TFMTBCDField;
    dstParametrosPAR_NMCEDE: TStringField;
    dstParametrosPAR_LOCPAGA: TStringField;
    dstParametrosPAR_NRBOLE: TFMTBCDField;
    dstParametrosPAR_PEJURO: TFMTBCDField;
    dstParametrosPAR_NATVEN: TStringField;
    dstParametrosPAR_DTFATU: TDateField;
    dstParametrosPAR_QTATRA: TFMTBCDField;
    dstParametrosPAR_NMPAST: TStringField;
    dstParametrosPAR_CDCEDE: TStringField;
    dstParametrosPAR_DIGCED: TStringField;
    dstParametrosPAR_CDBANC: TStringField;
    dstParametrosPAR_CDAGEN: TStringField;
    dstParametrosPAR_DIGAGE: TStringField;
    dstParametrosPAR_NRCONT: TStringField;
    dstParametrosPAR_INSTR1: TMemoField;
    dstParametrosPAR_INSTR2: TMemoField;
    dstParametrosPAR_IMLOGO: TBlobField;
    dstClientesCLI_CDCLIE: TStringField;
    dstClientesCLI_NMCLIE: TStringField;
    dstClientesCLI_NMCART: TStringField;
    dstClientesCLI_TPPESS: TStringField;
    dstClientesCLI_DTNASC: TDateField;
    dstClientesCLI_DTNAS1: TStringField;
    dstClientesCLI_SXCLIE: TStringField;
    dstClientesCLI_ESTCIV: TStringField;
    dstClientesCLI_NRIDEN: TStringField;
    dstClientesCLI_ORGEMI: TStringField;
    dstClientesCLI_UFEMIS: TStringField;
    dstClientesCLI_CPFCGC: TStringField;
    dstClientesCLI_EMAIL: TStringField;
    dstClientesCLI_NOMPAI: TStringField;
    dstClientesCLI_NOMMAE: TStringField;
    dstClientesCLI_CDBANC: TStringField;
    dstClientesCLI_FLESPE: TStringField;
    dstClientesCLI_ENCLIE: TStringField;
    dstClientesCLI_CEPCLI: TStringField;
    dstClientesCLI_COMCLI: TStringField;
    dstClientesCLI_BAICLI: TStringField;
    dstClientesCLI_CIDCLI: TStringField;
    dstClientesCLI_UFCLIE: TStringField;
    dstClientesCLI_FONCLI: TStringField;
    dstClientesCLI_TIPFON: TStringField;
    dstClientesCLI_CELCLI: TStringField;
    dstClientesCLI_TPRESI: TStringField;
    dstClientesCLI_TMRESI: TStringField;
    dstClientesCLI_VLRESI: TFloatField;
    dstClientesCLI_NMEMPR: TStringField;
    dstClientesCLI_ENEMPR: TStringField;
    dstClientesCLI_CEPEMP: TStringField;
    dstClientesCLI_BAEMPR: TStringField;
    dstClientesCLI_CIEMPR: TStringField;
    dstClientesCLI_VINEMP: TStringField;
    dstClientesCLI_TIPEMP: TStringField;
    dstClientesCLI_TMSERV: TStringField;
    dstClientesCLI_VLSALA: TFloatField;
    dstClientesCLI_VLOUTR: TFloatField;
    dstClientesCLI_FONEMP: TStringField;
    dstClientesCLI_RAMEMP: TStringField;
    dstClientesCLI_FLPROP: TStringField;
    dstClientesCLI_NMCARG: TStringField;
    dstClientesCLI_CGCEMP: TStringField;
    dstClientesCLI_NOMCJG: TStringField;
    dstClientesCLI_EMPCJG: TStringField;
    dstClientesCLI_FONCJG: TStringField;
    dstClientesCLI_CELCJG: TStringField;
    dstClientesCLI_CPFCJG: TStringField;
    dstClientesCLI_ENCORR: TStringField;
    dstClientesCLI_NMBENS: TStringField;
    dstClientesCLI_VLBENS: TFloatField;
    dstClientesCLI_OUTCAR: TStringField;
    dstClientesCLI_NMREF1: TStringField;
    dstClientesCLI_FOREF1: TStringField;
    dstClientesCLI_NMREF2: TStringField;
    dstClientesCLI_FOREF2: TStringField;
    dstClientesCLI_DTCADA: TDateField;
    dstClientesCLI_DTCAD1: TStringField;
    dstClientesCLI_HOCADA: TStringField;
    dstClientesCLI_FLSITU: TStringField;
    dstClientesCLI_CDREPR: TStringField;
    dstClientesCLI_DATANA: TDateField;
    dstClientesCLI_DATAN1: TStringField;
    dstClientesCLI_HORANA: TStringField;
    dstClientesCLI_USUANA: TStringField;
    dstClientesCLI_SPCANA: TStringField;
    dstClientesCLI_LOCANA: TStringField;
    dstClientesCLI_OBSANA: TBlobField;
    dstClientesCLI_LIMANA: TFloatField;
    dstClientesCLI_FLCONV: TStringField;
    dstClientesCLI_NRCART: TStringField;
    dstClientesCLI_PEDESC: TFMTBCDField;
    dstClientesCLI_CDUSUA: TStringField;
    dstBuscaClienteCLI_CDCLIE: TStringField;
    dstBuscaClienteCLI_NMCLIE: TStringField;
    dstBuscaClienteCLI_NMCART: TStringField;
    dstBuscaClienteCLI_TPPESS: TStringField;
    dstBuscaClienteCLI_DTNASC: TDateField;
    dstBuscaClienteCLI_DTNAS1: TStringField;
    dstBuscaClienteCLI_SXCLIE: TStringField;
    dstBuscaClienteCLI_ESTCIV: TStringField;
    dstBuscaClienteCLI_NRIDEN: TStringField;
    dstBuscaClienteCLI_ORGEMI: TStringField;
    dstBuscaClienteCLI_UFEMIS: TStringField;
    dstBuscaClienteCLI_CPFCGC: TStringField;
    dstBuscaClienteCLI_EMAIL: TStringField;
    dstBuscaClienteCLI_NOMPAI: TStringField;
    dstBuscaClienteCLI_NOMMAE: TStringField;
    dstBuscaClienteCLI_CDBANC: TStringField;
    dstBuscaClienteCLI_FLESPE: TStringField;
    dstBuscaClienteCLI_ENCLIE: TStringField;
    dstBuscaClienteCLI_CEPCLI: TStringField;
    dstBuscaClienteCLI_COMCLI: TStringField;
    dstBuscaClienteCLI_BAICLI: TStringField;
    dstBuscaClienteCLI_CIDCLI: TStringField;
    dstBuscaClienteCLI_UFCLIE: TStringField;
    dstBuscaClienteCLI_FONCLI: TStringField;
    dstBuscaClienteCLI_TIPFON: TStringField;
    dstBuscaClienteCLI_CELCLI: TStringField;
    dstBuscaClienteCLI_TPRESI: TStringField;
    dstBuscaClienteCLI_TMRESI: TStringField;
    dstBuscaClienteCLI_VLRESI: TFloatField;
    dstBuscaClienteCLI_NMEMPR: TStringField;
    dstBuscaClienteCLI_ENEMPR: TStringField;
    dstBuscaClienteCLI_CEPEMP: TStringField;
    dstBuscaClienteCLI_BAEMPR: TStringField;
    dstBuscaClienteCLI_CIEMPR: TStringField;
    dstBuscaClienteCLI_VINEMP: TStringField;
    dstBuscaClienteCLI_TIPEMP: TStringField;
    dstBuscaClienteCLI_TMSERV: TStringField;
    dstBuscaClienteCLI_VLSALA: TFloatField;
    dstBuscaClienteCLI_VLOUTR: TFloatField;
    dstBuscaClienteCLI_FONEMP: TStringField;
    dstBuscaClienteCLI_RAMEMP: TStringField;
    dstBuscaClienteCLI_FLPROP: TStringField;
    dstBuscaClienteCLI_NMCARG: TStringField;
    dstBuscaClienteCLI_CGCEMP: TStringField;
    dstBuscaClienteCLI_NOMCJG: TStringField;
    dstBuscaClienteCLI_EMPCJG: TStringField;
    dstBuscaClienteCLI_FONCJG: TStringField;
    dstBuscaClienteCLI_CELCJG: TStringField;
    dstBuscaClienteCLI_CPFCJG: TStringField;
    dstBuscaClienteCLI_ENCORR: TStringField;
    dstBuscaClienteCLI_NMBENS: TStringField;
    dstBuscaClienteCLI_VLBENS: TFloatField;
    dstBuscaClienteCLI_OUTCAR: TStringField;
    dstBuscaClienteCLI_NMREF1: TStringField;
    dstBuscaClienteCLI_FOREF1: TStringField;
    dstBuscaClienteCLI_NMREF2: TStringField;
    dstBuscaClienteCLI_FOREF2: TStringField;
    dstBuscaClienteCLI_DTCADA: TDateField;
    dstBuscaClienteCLI_DTCAD1: TStringField;
    dstBuscaClienteCLI_HOCADA: TStringField;
    dstBuscaClienteCLI_FLSITU: TStringField;
    dstBuscaClienteCLI_CDREPR: TStringField;
    dstBuscaClienteCLI_DATANA: TDateField;
    dstBuscaClienteCLI_DATAN1: TStringField;
    dstBuscaClienteCLI_HORANA: TStringField;
    dstBuscaClienteCLI_USUANA: TStringField;
    dstBuscaClienteCLI_SPCANA: TStringField;
    dstBuscaClienteCLI_LOCANA: TStringField;
    dstBuscaClienteCLI_OBSANA: TBlobField;
    dstBuscaClienteCLI_LIMANA: TFloatField;
    dstBuscaClienteCLI_FLCONV: TStringField;
    dstBuscaClienteCLI_NRCART: TStringField;
    dstBuscaClienteCLI_PEDESC: TFMTBCDField;
    dstBuscaClienteCLI_CDUSUA: TStringField;
    dstCredenciadosCRE_CDCRED: TStringField;
    dstCredenciadosCRE_NMCRED: TStringField;
    dstCredenciadosCRE_NMEXTR: TStringField;
    dstCredenciadosCRE_ENDCRE: TStringField;
    dstCredenciadosCRE_BACRED: TStringField;
    dstCredenciadosCRE_CICRED: TStringField;
    dstCredenciadosCRE_UFCRED: TStringField;
    dstCredenciadosCRE_CEPCRE: TStringField;
    dstCredenciadosCRE_NRFONE: TStringField;
    dstCredenciadosCRE_CDUSUA: TStringField;
    dstBuscaCredCRE_CDCRED: TStringField;
    dstBuscaCredCRE_NMCRED: TStringField;
    dstBuscaCredCRE_NMEXTR: TStringField;
    dstBuscaCredCRE_ENDCRE: TStringField;
    dstBuscaCredCRE_BACRED: TStringField;
    dstBuscaCredCRE_CICRED: TStringField;
    dstBuscaCredCRE_UFCRED: TStringField;
    dstBuscaCredCRE_CEPCRE: TStringField;
    dstBuscaCredCRE_NRFONE: TStringField;
    dstBuscaCredCRE_CDUSUA: TStringField;
    dstCartoesCAR_NRCART: TStringField;
    dstCartoesCAR_CDCLIE: TStringField;
    dstCartoesCAR_NMCLIE: TStringField;
    dstCartoesCAR_DTEMIS: TDateField;
    dstCartoesCAR_DTEMI1: TStringField;
    dstCartoesCAR_DTVALI: TStringField;
    dstCartoesCAR_VLLIMI: TFMTBCDField;
    dstCartoesCAR_VLUTIL: TFloatField;
    dstCartoesCAR_DIAFAT: TIntegerField;
    dstCartoesCAR_FLDEPE: TStringField;
    dstCartoesCAR_FLSITU: TStringField;
    dstCartoesCAR_DTUTIL: TDateField;
    dstCartoesCAR_DTUTI1: TStringField;
    dstCartoesCAR_HOUTIL: TStringField;
    dstCartoesCAR_VLANTE: TFMTBCDField;
    dstCartoesCAR_VLCRED: TFMTBCDField;
    dstCartoesCAR_DTPAGA: TDateField;
    dstCartoesCAR_DTPAG1: TStringField;
    dstCartoesCAR_CDUSUA: TStringField;
    dstDebitoDEB_NRVEND: TStringField;
    dstDebitoDEB_NRCART: TStringField;
    dstDebitoDEB_CDCLIE: TStringField;
    dstDebitoDEB_CDCRED: TStringField;
    dstDebitoDEB_DTREFE: TStringField;
    dstDebitoDEB_QTPARC: TIntegerField;
    dstDebitoDEB_NRPARC: TIntegerField;
    dstDebitoDEB_VLPARC: TFloatField;
    dstDebitoDEB_DTVENC: TDateField;
    dstDebitoDEB_DTVEN1: TStringField;
    dstDebitoDEB_DTFATU: TDateField;
    dstDebitoDEB_DTFAT1: TStringField;
    dstDebitoDEB_TPMOVI: TStringField;
    dstDebitoDEB_FLSITU: TStringField;
    dstDebitoDEB_NRFATU: TStringField;
    dstDebitoDEB_VLDESC: TFloatField;
    dstBoletos: TSQLDataSet;
    dspBoletos: TDataSetProvider;
    cdsBoletos: TClientDataSet;
    dstMovBoletos: TSQLDataSet;
    dspMovBoletos: TDataSetProvider;
    cdsMovBoletos: TClientDataSet;
    dstBoletosBOL_NRDOCU: TStringField;
    dstBoletosBOL_NRFATU: TStringField;
    dstBoletosBOL_NRCART: TStringField;
    dstBoletosBOL_LOCPAG: TStringField;
    dstBoletosBOL_DTVENC: TDateField;
    dstBoletosBOL_NMCEDE: TStringField;
    dstBoletosBOL_DTDOCU: TDateField;
    dstBoletosBOL_ACEITE: TStringField;
    dstBoletosBOL_VLDOCU: TFloatField;
    dstBoletosBOL_NMSACA: TStringField;
    dstBoletosBOL_ENDERE: TStringField;
    dstBoletosBOL_COMPLE: TStringField;
    dstBoletosBOL_CEPSAC: TStringField;
    dstBoletosBOL_BAIRRO: TStringField;
    dstBoletosBOL_CIDADE: TStringField;
    dstBoletosBOL_UFSACA: TStringField;
    dstBoletosBOL_CPFCGC: TStringField;
    dstBoletosBOL_TPPESS: TStringField;
    dstBoletosBOL_VLANTE: TFloatField;
    dstBoletosBOL_VLCRED: TFloatField;
    dstBoletosBOL_VLREST: TFloatField;
    dstBoletosBOL_VLFATU: TFloatField;
    dstBoletosBOL_FLSITU: TStringField;
    dstBoletosBOL_VLJURO: TFloatField;
    dstBoletosBOL_VLMULT: TFloatField;
    dstBoletosBOL_VLDESC: TFloatField;
    dstBoletosBOL_DTPAGA: TDateField;
    dstBoletosBOL_DTPAG1: TStringField;
    dstBoletosBOL_VLPAGO: TFloatField;
    dstBoletosBOL_CDUSUA: TStringField;
    dstBoletosBOL_CDCLIE: TStringField;
    dstBoletosBOL_VLLIQU: TFloatField;
    dstBoletosBOL_DTCRED: TDateField;
    dstBoletosBOL_DTCRE1: TStringField;
    dstBoletosBOL_TPBAIX: TStringField;
    dstBoletosBOL_QTIMPR: TFMTBCDField;
    dstBoletosBOL_OBSERV: TStringField;
    dstBoletosBOL_USEDIT: TStringField;
    dstBoletosBOL_DTEDIT: TDateField;
    dstBoletosBOL_DTEDI1: TStringField;
    dstBoletosBOL_HOEDIT: TStringField;
    dstBoletosBOL_MOTIV1: TStringField;
    dstBoletosBOL_MOTIV2: TStringField;
    dstBoletosBOL_MOTIV3: TStringField;
    cdsBoletosBOL_NRDOCU: TStringField;
    cdsBoletosBOL_NRFATU: TStringField;
    cdsBoletosBOL_NRCART: TStringField;
    cdsBoletosBOL_LOCPAG: TStringField;
    cdsBoletosBOL_DTVENC: TDateField;
    cdsBoletosBOL_NMCEDE: TStringField;
    cdsBoletosBOL_DTDOCU: TDateField;
    cdsBoletosBOL_ACEITE: TStringField;
    cdsBoletosBOL_VLDOCU: TFloatField;
    cdsBoletosBOL_NMSACA: TStringField;
    cdsBoletosBOL_ENDERE: TStringField;
    cdsBoletosBOL_COMPLE: TStringField;
    cdsBoletosBOL_CEPSAC: TStringField;
    cdsBoletosBOL_BAIRRO: TStringField;
    cdsBoletosBOL_CIDADE: TStringField;
    cdsBoletosBOL_UFSACA: TStringField;
    cdsBoletosBOL_CPFCGC: TStringField;
    cdsBoletosBOL_TPPESS: TStringField;
    cdsBoletosBOL_VLANTE: TFloatField;
    cdsBoletosBOL_VLCRED: TFloatField;
    cdsBoletosBOL_VLREST: TFloatField;
    cdsBoletosBOL_VLFATU: TFloatField;
    cdsBoletosBOL_FLSITU: TStringField;
    cdsBoletosBOL_VLJURO: TFloatField;
    cdsBoletosBOL_VLMULT: TFloatField;
    cdsBoletosBOL_VLDESC: TFloatField;
    cdsBoletosBOL_DTPAGA: TDateField;
    cdsBoletosBOL_DTPAG1: TStringField;
    cdsBoletosBOL_VLPAGO: TFloatField;
    cdsBoletosBOL_CDUSUA: TStringField;
    cdsBoletosBOL_CDCLIE: TStringField;
    cdsBoletosBOL_VLLIQU: TFloatField;
    cdsBoletosBOL_DTCRED: TDateField;
    cdsBoletosBOL_DTCRE1: TStringField;
    cdsBoletosBOL_TPBAIX: TStringField;
    cdsBoletosBOL_QTIMPR: TFMTBCDField;
    cdsBoletosBOL_OBSERV: TStringField;
    cdsBoletosBOL_USEDIT: TStringField;
    cdsBoletosBOL_DTEDIT: TDateField;
    cdsBoletosBOL_DTEDI1: TStringField;
    cdsBoletosBOL_HOEDIT: TStringField;
    cdsBoletosBOL_MOTIV1: TStringField;
    cdsBoletosBOL_MOTIV2: TStringField;
    cdsBoletosBOL_MOTIV3: TStringField;
    dstMovBoletosBOM_NRFATU: TStringField;
    dstMovBoletosBOM_NRCART: TStringField;
    dstMovBoletosBOM_CDCLIE: TStringField;
    dstMovBoletosBOM_DTREFE: TStringField;
    dstMovBoletosBOM_NMCRED: TStringField;
    dstMovBoletosBOM_NMPLAN: TStringField;
    dstMovBoletosBOM_VLPARC: TFloatField;
    dstMovBoletosBOM_TPMOVI: TStringField;
    cdsMovBoletosBOM_NRFATU: TStringField;
    cdsMovBoletosBOM_NRCART: TStringField;
    cdsMovBoletosBOM_CDCLIE: TStringField;
    cdsMovBoletosBOM_DTREFE: TStringField;
    cdsMovBoletosBOM_NMCRED: TStringField;
    cdsMovBoletosBOM_NMPLAN: TStringField;
    cdsMovBoletosBOM_VLPARC: TFloatField;
    cdsMovBoletosBOM_TPMOVI: TStringField;
    dstFeriados: TSQLDataSet;
    dspFeriados: TDataSetProvider;
    cdsFeriados: TClientDataSet;
    dstFeriadosFER_DTFERI: TStringField;
    dstFeriadosFER_NMDESC: TStringField;
    cdsFeriadosFER_DTFERI: TStringField;
    cdsFeriadosFER_NMDESC: TStringField;
    dstDiaFaturaFAT_DIAFATU: TIntegerField;
    dstDiaFaturaFAT_NMDESC: TStringField;
    dstDebitoDEB_DTMOVI: TDateField;
    dstDebitoDEB_DTMOV1: TStringField;
    cdsDebitoDEB_DTMOVI: TDateField;
    cdsDebitoDEB_DTMOV1: TStringField;
    dstParametrosPAR_PEMULT: TFMTBCDField;
    cdsParametrosPAR_PEMULT: TFMTBCDField;
    dstDebitoDEB_DIAFAT: TStringField;
    cdsDebitoDEB_DIAFAT: TStringField;
    dstCaixa: TSQLDataSet;
    dspCaixa: TDataSetProvider;
    dstCaixaCAI_CDMODA: TStringField;
    dstCaixaCAI_VLMODA: TFloatField;
    cdsCaixa: TClientDataSet;
    cdsCaixaCAI_CDMODA: TStringField;
    cdsCaixaCAI_VLMODA: TFloatField;
    dstModalidade: TSQLDataSet;
    dstModalidadeMOD_CDMODA: TStringField;
    dstModalidadeMOD_NMMODA: TStringField;
    dstModalidadeMOD_NMABRE: TStringField;
    dspModalidade: TDataSetProvider;
    cdsModalidade: TClientDataSet;
    cdsModalidadeMOD_CDMODA: TStringField;
    cdsModalidadeMOD_NMMODA: TStringField;
    cdsModalidadeMOD_NMABRE: TStringField;
    dstMovCaixa: TSQLDataSet;
    dspMovCaixa: TDataSetProvider;
    cdsMovCaixa: TClientDataSet;
    dstMovCaixaMCA_NRSEQU: TStringField;
    dstMovCaixaMCA_NRDOCU: TStringField;
    dstMovCaixaMCA_CDNATU: TStringField;
    dstMovCaixaMCA_DTMOVI: TDateField;
    dstMovCaixaMCA_DTMOV1: TStringField;
    dstMovCaixaMCA_DTREFE: TStringField;
    dstMovCaixaMCA_HOMOVI: TStringField;
    dstMovCaixaMCA_TPMOVI: TStringField;
    dstMovCaixaMCA_CDMODA: TStringField;
    dstMovCaixaMCA_VLMODA: TFloatField;
    dstMovCaixaMCA_NMDESC: TStringField;
    dstMovCaixaMCA_CDFUNC: TStringField;
    cdsMovCaixaMCA_NRSEQU: TStringField;
    cdsMovCaixaMCA_NRDOCU: TStringField;
    cdsMovCaixaMCA_CDNATU: TStringField;
    cdsMovCaixaMCA_DTMOVI: TDateField;
    cdsMovCaixaMCA_DTMOV1: TStringField;
    cdsMovCaixaMCA_DTREFE: TStringField;
    cdsMovCaixaMCA_HOMOVI: TStringField;
    cdsMovCaixaMCA_TPMOVI: TStringField;
    cdsMovCaixaMCA_CDMODA: TStringField;
    cdsMovCaixaMCA_VLMODA: TFloatField;
    cdsMovCaixaMCA_NMDESC: TStringField;
    cdsMovCaixaMCA_CDFUNC: TStringField;
    cdsBuscaClienteCLI_ENCLIE: TStringField;
    cdsBuscaClienteCLI_BAICLI: TStringField;
    dstMovimentoMOV_NRVEND: TStringField;
    dstMovimentoMOV_NRCART: TStringField;
    dstMovimentoMOV_CDCRED: TStringField;
    dstMovimentoMOV_DTMOVI: TDateField;
    dstMovimentoMOV_HOMOVI: TStringField;
    dstMovimentoMOV_VLLIMI: TFloatField;
    dstMovimentoMOV_VLUTIL: TFloatField;
    dstMovimentoMOV_VLVEND: TFloatField;
    dstMovimentoMOV_QTPARC: TIntegerField;
    dstMovimentoMOV_FLSITU: TStringField;
    dstMovimentoMOV_CDOPER: TStringField;
    dstMovimentoMOV_DTCANC: TDateField;
    dstMovimentoMOV_HOCANC: TStringField;
    dstMovimentoMOV_OPCANC: TStringField;
    cdsMovimentoMOV_NRVEND: TStringField;
    cdsMovimentoMOV_NRCART: TStringField;
    cdsMovimentoMOV_CDCRED: TStringField;
    cdsMovimentoMOV_DTMOVI: TDateField;
    cdsMovimentoMOV_HOMOVI: TStringField;
    cdsMovimentoMOV_VLLIMI: TFloatField;
    cdsMovimentoMOV_VLUTIL: TFloatField;
    cdsMovimentoMOV_VLVEND: TFloatField;
    cdsMovimentoMOV_QTPARC: TIntegerField;
    cdsMovimentoMOV_FLSITU: TStringField;
    cdsMovimentoMOV_CDOPER: TStringField;
    cdsMovimentoMOV_DTCANC: TDateField;
    cdsMovimentoMOV_HOCANC: TStringField;
    cdsMovimentoMOV_OPCANC: TStringField;
    qryIncVenda: TSQLQuery;
    qryLocCartao: TSQLQuery;
    qryLocCartaoCAR_NRCART: TStringField;
    qryLocCartaoCAR_CDCLIE: TStringField;
    qryLocCartaoCAR_NMCLIE: TStringField;
    qryLocCartaoCAR_VLLIMI: TFMTBCDField;
    qryLocCartaoCAR_VLUTIL: TFloatField;
    qryLocCartaoCAR_DIAFAT: TIntegerField;
    qryLocCartaoCAR_FLSITU: TStringField;
    qryLocCartaoCAR_DTUTIL: TDateField;
    qryLocCartaoCAR_DTUTI1: TStringField;
    qryLocCartaoCAR_HOUTIL: TStringField;
    qryLocCartaoCAR_VLANTE: TFMTBCDField;
    qryLocCartaoCAR_VLCRED: TFMTBCDField;
    qryLocCartaoCAR_DTVALI: TStringField;
    qryBuscaCliente: TSQLQuery;
    qryBuscaClienteCLI_CDCLIE: TStringField;
    qryBuscaClienteCLI_NMCLIE: TStringField;
    qryBuscaClienteCLI_NMCART: TStringField;
    qryBuscaClienteCLI_TPPESS: TStringField;
    qryBuscaClienteCLI_DTNASC: TDateField;
    qryBuscaClienteCLI_DTNAS1: TStringField;
    qryBuscaClienteCLI_SXCLIE: TStringField;
    qryBuscaClienteCLI_ESTCIV: TStringField;
    qryBuscaClienteCLI_NRIDEN: TStringField;
    qryBuscaClienteCLI_ORGEMI: TStringField;
    qryBuscaClienteCLI_UFEMIS: TStringField;
    qryBuscaClienteCLI_CPFCGC: TStringField;
    qryBuscaClienteCLI_NOMPAI: TStringField;
    qryBuscaClienteCLI_NOMMAE: TStringField;
    qryBuscaClienteCLI_FLSITU: TStringField;
    qryCredeciado: TSQLQuery;
    qryAtualizaCartao: TSQLQuery;
    qryDebito: TSQLQuery;
    qryLocVenda: TSQLQuery;
    qryAtualizaDebito: TSQLQuery;
    qryLocCartaoCAR_NMSITU: TStringField;
    qrySitucao: TSQLQuery;
    qrySituacaoCartao: TSQLQuery;
    qrySituacaoCartaoSIT_SIGSIT: TStringField;
    qrySituacaoCartaoSIT_NMSITU: TStringField;
    dstUsuarios: TSQLDataSet;
    dspUsuarios: TDataSetProvider;
    cdsUsuarios: TClientDataSet;
    dstUsuariosSEN_CDUSUA: TStringField;
    dstUsuariosSEN_NMUSUA: TStringField;
    dstUsuariosSEN_SNATUA: TStringField;
    dstUsuariosSEN_NMCARG: TStringField;
    dstUsuariosSEN_NMTERM: TStringField;
    dstUsuariosSEN_FLSUPE: TStringField;
    dstUsuariosSEN_CDGRUP: TStringField;
    dstUsuariosSEN_DTATUA: TDateField;
    dstUsuariosSEN_DTATU1: TStringField;
    dstUsuariosSEN_FLEXCL: TStringField;
    dstUsuariosSEN_FLLOGA: TStringField;
    cdsUsuariosSEN_CDUSUA: TStringField;
    cdsUsuariosSEN_NMUSUA: TStringField;
    cdsUsuariosSEN_SNATUA: TStringField;
    cdsUsuariosSEN_NMCARG: TStringField;
    cdsUsuariosSEN_NMTERM: TStringField;
    cdsUsuariosSEN_FLSUPE: TStringField;
    cdsUsuariosSEN_CDGRUP: TStringField;
    cdsUsuariosSEN_DTATUA: TDateField;
    cdsUsuariosSEN_DTATU1: TStringField;
    cdsUsuariosSEN_FLEXCL: TStringField;
    cdsUsuariosSEN_FLLOGA: TStringField;
    cdsCartoesCAR_NMCLIE: TStringField;
    procedure DataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  public
    function ValidaCampo(Table: TClientDataSet; Campo, Text: String): Boolean;
    function ValidaCampo2(Campo, Text: String): Boolean;
    function ValidaNomeCred(Campo, Text: String): Boolean;
    function mvcodigo(campo,tabela:string):integer;
    function mscodigo(campo,tabela:string):string;
    { Public declarations }
  end;

var
  dmInfoCartao: TdmInfoCartao;

implementation

{$R *.dfm}

{ TdmInfoCartao }

function TdmInfoCartao.ValidaCampo(Table: TClientDataSet; Campo,
  Text: String): Boolean;
Var
  dstTabela : TSQLDataSet;
  Tabela  : TClientDataSet;
  ProName : TDataSetProvider;
begin
    dstTabela := TSQLDataSet.Create(Application);
    dstTabela.SQLConnection := SQLConnection1;
    dstTabela.CommandText   := 'Select * from ACCCLI order by CLI_NMCLIE';
    dstTabela.Open;
    //
    ProName := TDataSetProvider.Create(Application);
    ProName.DataSet := dstTabela;
    //
    Tabela := TClientDataSet.Create(Application);
    Tabela.ProviderName := 'ProName';
    Tabela.Open;
    If Not(Tabela.Locate(Campo,Text,[])) Then
    begin
        result := False;
        Tabela.Free;
    end
    Else
    Begin
        result := True;
        Tabela.Free;
    End;
    // Fecha as tabelas
    Tabela.Close;
    dstTabela.Close;
end;

function TdmInfoCartao.ValidaCampo2(Campo, Text: String): Boolean;
begin
    cdsBuscaCliente.Open;
    //
    If Not(cdsBuscaCliente.Locate(Campo,Text,[])) Then
    begin
        result := False;
        //cdsBuscaCliente.Free;
    end
    Else
    Begin
        result := True;
        //cdsBuscaCliente.Free;
    End;
    // Fecha as tabelas
   { cdsBuscaCliente.Close;
    dstBuscaCliente.Close;}
end;

function TdmInfoCartao.ValidaNomeCred(Campo, Text: String): Boolean;
begin
    cdsBuscaCred.Open;
    //
    If Not(cdsBuscaCred.Locate(Campo,Text,[])) Then
        result := False
    Else
        result := True;
end;

procedure TdmInfoCartao.DataModuleCreate(Sender: TObject);
begin
     Try
          SQLConnection1.Connected := True;
     Except
        on Exc:Exception do
        begin
           Application.MessageBox(PChar('Erro ao tentar conectar Banco de Dados!!!.'+#13
                      + Exc.Message),
                      'ATENÇÃO', MB_OK+MB_ICONSTOP+MB_APPLMODAL);
        End;
     End;

end;

function TdmInfoCartao.mscodigo(campo, tabela: string): string;
var qraux : TSQLquery;
    texto : string;
begin
  texto := 'Select min('+campo+') from '+tabela;
  QrAux := TSqlquery.Create(nil);
  with QrAux do
    try
      SQLConnection := SQLConnection1;
      sql.Add(texto);
      open;
      result := fields[0].AsString;
    finally
      free;
    end;
end;

function TdmInfoCartao.mvcodigo(campo, tabela: string): integer;
var qraux : TSQLquery;
    texto : string;
begin
  texto := 'Select min('+campo+') from '+tabela;
  QrAux := TSqlquery.Create(nil);
  with QrAux do
    try
      SQLConnection := SQLConnection1;
      sql.Add(texto);
      open;
      result := fields[0].AsInteger;
    finally
      free;
    end;
end;

end.
